default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jesher
  password: jesher
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: lms_development

test:
  <<: *default
  database: lms_test

production:
  <<: *default
  database: lms_production
  username: jesher
  password: <%= ENV["lms_DATABASE_PASSWORD"] %>
  